package noesis.jmeter.main;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;

import us.abstracta.jmeter.javadsl.core.DslTestPlan;

public class ExternalKeyword {
	public static String COOKIE_JAVA_VALUE = "COOKIE_JAVA_VALUE";
	public static String FILENAMETEMP_DIR = "C:/QM_NTX/JMETER_TEMP.jmx";

	public void testPerformance(String cookie, String fileContent) throws IOException {
		fileContent = fileContent.replaceAll(COOKIE_JAVA_VALUE, cookie);
		FileWriter fw = new FileWriter(new File(FILENAMETEMP_DIR));
		fw.append(fileContent);
		fw.close();
		final DslTestPlan jmx = DslTestPlan.fromJmx(FILENAMETEMP_DIR);
		jmx.run(); jmx.showInGui();
	}

	public void testPerformanceByDir(String cookie, String fileDir) throws IOException {
		String fileContent = getFileContent(fileDir).replaceAll(COOKIE_JAVA_VALUE, cookie);
		testPerformance(cookie, fileContent);
	}

	public static String getFileContent(String fileDir) throws IOException {
		return new String(Files.readAllBytes(new File(fileDir).toPath()));
	}

	public static void main(String[] args) throws IOException {
		new ExternalKeyword().testPerformance("4B450555A76F4F2F1DE78739474DD50A", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
				+ "<jmeterTestPlan version=\"1.2\" properties=\"5.0\" jmeter=\"5.5\">\r\n"
				+ "   <hashTree>\r\n"
				+ "      <TestPlan guiclass=\"TestPlanGui\" testclass=\"TestPlan\" testname=\"Plano de Teste\" enabled=\"true\">\r\n"
				+ "         <stringProp name=\"TestPlan.comments\" />\r\n"
				+ "         <boolProp name=\"TestPlan.functional_mode\">false</boolProp>\r\n"
				+ "         <boolProp name=\"TestPlan.serialize_threadgroups\">false</boolProp>\r\n"
				+ "         <elementProp name=\"TestPlan.user_defined_variables\" elementType=\"Arguments\" guiclass=\"ArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\r\n"
				+ "            <collectionProp name=\"Arguments.arguments\">\r\n"
				+ "               <elementProp name=\"SCRIPT_PATH\" elementType=\"Argument\">\r\n"
				+ "                  <stringProp name=\"Argument.name\">SCRIPT_PATH</stringProp>\r\n"
				+ "                  <stringProp name=\"Argument.value\">${__BeanShell(import org.apache.jmeter.services.FileServer;\"C:/QM_NTX\")}${__BeanShell(File.separator,)}</stringProp>\r\n"
				+ "                  <stringProp name=\"Argument.metadata\">=</stringProp>\r\n"
				+ "               </elementProp>\r\n"
				+ "            </collectionProp>\r\n"
				+ "         </elementProp>\r\n"
				+ "         <stringProp name=\"TestPlan.user_define_classpath\" />\r\n"
				+ "         <boolProp name=\"TestPlan.tearDown_on_shutdown\">true</boolProp>\r\n"
				+ "      </TestPlan>\r\n"
				+ "      <hashTree>\r\n"
				+ "         <Arguments guiclass=\"ArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\r\n"
				+ "            <collectionProp name=\"Arguments.arguments\">\r\n"
				+ "               <elementProp name=\"host\" elementType=\"Argument\">\r\n"
				+ "                  <stringProp name=\"Argument.name\">host</stringProp>\r\n"
				+ "                  <stringProp name=\"Argument.value\">http://timntx.brazilsouth.cloudapp.azure.com:8084/NTX/ntxLogin</stringProp>\r\n"
				+ "                  <stringProp name=\"Argument.metadata\">=</stringProp>\r\n"
				+ "               </elementProp>\r\n"
				+ "               <elementProp name=\"scheme\" elementType=\"Argument\">\r\n"
				+ "                  <stringProp name=\"Argument.name\">scheme</stringProp>\r\n"
				+ "                  <stringProp name=\"Argument.value\">https</stringProp>\r\n"
				+ "                  <stringProp name=\"Argument.metadata\">=</stringProp>\r\n"
				+ "               </elementProp>\r\n"
				+ "            </collectionProp>\r\n"
				+ "         </Arguments>\r\n"
				+ "         <hashTree />\r\n"
				+ "         <ConfigTestElement guiclass=\"HttpDefaultsGui\" testclass=\"ConfigTestElement\" testname=\"HTTP Request Defaults\" enabled=\"true\">\r\n"
				+ "            <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\r\n"
				+ "               <collectionProp name=\"Arguments.arguments\" />\r\n"
				+ "            </elementProp>\r\n"
				+ "            <stringProp name=\"HTTPSampler.domain\">http://timntx.brazilsouth.cloudapp.azure.com:8084/NTX/ntxLogin</stringProp>\r\n"
				+ "            <stringProp name=\"HTTPSampler.port\" />\r\n"
				+ "            <stringProp name=\"HTTPSampler.protocol\">https</stringProp>\r\n"
				+ "            <stringProp name=\"HTTPSampler.contentEncoding\" />\r\n"
				+ "            <stringProp name=\"HTTPSampler.path\" />\r\n"
				+ "            <stringProp name=\"HTTPSampler.concurrentPool\">6</stringProp>\r\n"
				+ "            <stringProp name=\"HTTPSampler.connect_timeout\" />\r\n"
				+ "            <stringProp name=\"HTTPSampler.response_timeout\" />\r\n"
				+ "         </ConfigTestElement>\r\n"
				+ "         <hashTree />\r\n"
				+ "         <CookieManager guiclass=\"CookiePanel\" testclass=\"CookieManager\" testname=\"HTTP Cookie Manager\" enabled=\"true\">\r\n"
				+ "            <collectionProp name=\"CookieManager.cookies\">\r\n"
				+ "               <elementProp name=\"JSESSIONID\" elementType=\"Cookie\" testname=\"JSESSIONID\">\r\n"
				+ "                  <stringProp name=\"Cookie.value\">COOKIE_JAVA_VALUE</stringProp>\r\n"
				+ "                  <stringProp name=\"Cookie.domain\">timntx.brazilsouth.cloudapp.azure.com</stringProp>\r\n"
				+ "                  <stringProp name=\"Cookie.path\">/NTX</stringProp>\r\n"
				+ "                  <boolProp name=\"Cookie.secure\">false</boolProp>\r\n"
				+ "                  <longProp name=\"Cookie.expires\">0</longProp>\r\n"
				+ "                  <boolProp name=\"Cookie.path_specified\">true</boolProp>\r\n"
				+ "                  <boolProp name=\"Cookie.domain_specified\">true</boolProp>\r\n"
				+ "               </elementProp>\r\n"
				+ "            </collectionProp>\r\n"
				+ "            <boolProp name=\"CookieManager.clearEachIteration\">false</boolProp>\r\n"
				+ "            <boolProp name=\"CookieManager.controlledByThreadGroup\">false</boolProp>\r\n"
				+ "         </CookieManager>\r\n"
				+ "         <hashTree />\r\n"
				+ "         <ThreadGroup guiclass=\"ThreadGroupGui\" testclass=\"ThreadGroup\" testname=\"Grupo de Usuários\" enabled=\"true\">\r\n"
				+ "            <stringProp name=\"ThreadGroup.on_sample_error\">continue</stringProp>\r\n"
				+ "            <elementProp name=\"ThreadGroup.main_controller\" elementType=\"LoopController\" guiclass=\"LoopControlPanel\" testclass=\"LoopController\" testname=\"Loop Controller\" enabled=\"true\">\r\n"
				+ "               <boolProp name=\"LoopController.continue_forever\">false</boolProp>\r\n"
				+ "               <stringProp name=\"LoopController.loops\">1</stringProp>\r\n"
				+ "            </elementProp>\r\n"
				+ "            <stringProp name=\"ThreadGroup.num_threads\">1</stringProp>\r\n"
				+ "            <stringProp name=\"ThreadGroup.ramp_time\">1</stringProp>\r\n"
				+ "            <longProp name=\"ThreadGroup.start_time\">1370726934000</longProp>\r\n"
				+ "            <longProp name=\"ThreadGroup.end_time\">1370726934000</longProp>\r\n"
				+ "            <boolProp name=\"ThreadGroup.scheduler\">false</boolProp>\r\n"
				+ "            <stringProp name=\"ThreadGroup.duration\" />\r\n"
				+ "            <stringProp name=\"ThreadGroup.delay\" />\r\n"
				+ "            <boolProp name=\"ThreadGroup.same_user_on_next_iteration\">true</boolProp>\r\n"
				+ "         </ThreadGroup>\r\n"
				+ "         <hashTree>\r\n"
				+ "            <RecordingController guiclass=\"RecordController\" testclass=\"RecordingController\" testname=\"Recording Controller\" enabled=\"true\" />\r\n"
				+ "            <hashTree>\r\n"
				+ "               <TransactionController guiclass=\"TransactionControllerGui\" testclass=\"TransactionController\" testname=\"ntx\" enabled=\"true\">\r\n"
				+ "                  <boolProp name=\"TransactionController.includeTimers\">false</boolProp>\r\n"
				+ "                  <boolProp name=\"TransactionController.parent\">false</boolProp>\r\n"
				+ "               </TransactionController>\r\n"
				+ "               <hashTree>\r\n"
				+ "                  <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"ntx/NTX/ntxLogin-215\" enabled=\"true\">\r\n"
				+ "                     <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"Arguments.arguments\" />\r\n"
				+ "                     </elementProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.domain\">timntx.brazilsouth.cloudapp.azure.com</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.port\">8084</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.protocol\">http</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.contentEncoding\">UTF-8</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.path\">/NTX/ntxLogin</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.method\">GET</stringProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.embedded_url_re\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.connect_timeout\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.response_timeout\" />\r\n"
				+ "                  </HTTPSamplerProxy>\r\n"
				+ "                  <hashTree>\r\n"
				+ "                     <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" testname=\"HTTP Header Manager\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"HeaderManager.headers\">\r\n"
				+ "                           <elementProp name=\"Accept-Language\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Language</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Upgrade-Insecure-Requests\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Upgrade-Insecure-Requests</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">1</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept-Encoding\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Encoding</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">gzip, deflate</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"User-Agent\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">User-Agent</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                        </collectionProp>\r\n"
				+ "                     </HeaderManager>\r\n"
				+ "                     <hashTree />\r\n"
				+ "                  </hashTree>\r\n"
				+ "               </hashTree>\r\n"
				+ "               <TransactionController guiclass=\"TransactionControllerGui\" testclass=\"TransactionController\" testname=\"ntx\" enabled=\"true\">\r\n"
				+ "                  <boolProp name=\"TransactionController.includeTimers\">false</boolProp>\r\n"
				+ "                  <boolProp name=\"TransactionController.parent\">false</boolProp>\r\n"
				+ "               </TransactionController>\r\n"
				+ "               <hashTree>\r\n"
				+ "                  <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"ntx/NTX/ntxLogin?POSTOption=Login&amp;username=admin&amp;ntxUrl=http%3A%2F%2Ftimntx.brazilsouth.cloudapp.azure.com%3A8084%2FNTX%2FntxLogin&amp;auth=U2FsdGVkX1%2FeZrKDooqN0htVs2Po9NZ%2FEGMPOolHDw4%3D-231\" enabled=\"true\">\r\n"
				+ "                     <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"Arguments.arguments\" />\r\n"
				+ "                     </elementProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.domain\">timntx.brazilsouth.cloudapp.azure.com</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.port\">8084</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.protocol\">http</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.contentEncoding\">utf-8</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.path\">/NTX/ntxLogin?POSTOption=Login&amp;username=admin&amp;ntxUrl=http%3A%2F%2Ftimntx.brazilsouth.cloudapp.azure.com%3A8084%2FNTX%2FntxLogin&amp;auth=U2FsdGVkX1%2FeZrKDooqN0htVs2Po9NZ%2FEGMPOolHDw4%3D</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.method\">POST</stringProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.embedded_url_re\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.connect_timeout\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.response_timeout\" />\r\n"
				+ "                  </HTTPSamplerProxy>\r\n"
				+ "                  <hashTree>\r\n"
				+ "                     <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" testname=\"HTTP Header Manager\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"HeaderManager.headers\">\r\n"
				+ "                           <elementProp name=\"Referer\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Referer</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">${host}</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept-Language\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Language</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Origin\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Origin</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">http://timntx.brazilsouth.cloudapp.azure.com:8084</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"X-Requested-With\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">X-Requested-With</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">XMLHttpRequest</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept-Encoding\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Encoding</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">gzip, deflate</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"User-Agent\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">User-Agent</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">text/html, */*; q=0.01</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                        </collectionProp>\r\n"
				+ "                     </HeaderManager>\r\n"
				+ "                     <hashTree />\r\n"
				+ "                  </hashTree>\r\n"
				+ "                  <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"ntx/NTX/ntxIndexDashboard-232\" enabled=\"true\">\r\n"
				+ "                     <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"Arguments.arguments\" />\r\n"
				+ "                     </elementProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.domain\">timntx.brazilsouth.cloudapp.azure.com</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.port\">8084</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.protocol\">http</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.contentEncoding\">UTF-8</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.path\">/NTX/ntxIndexDashboard</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.method\">GET</stringProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.embedded_url_re\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.connect_timeout\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.response_timeout\" />\r\n"
				+ "                  </HTTPSamplerProxy>\r\n"
				+ "                  <hashTree>\r\n"
				+ "                     <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" testname=\"HTTP Header Manager\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"HeaderManager.headers\">\r\n"
				+ "                           <elementProp name=\"Referer\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Referer</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">${host}</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept-Language\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Language</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Upgrade-Insecure-Requests\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Upgrade-Insecure-Requests</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">1</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept-Encoding\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Encoding</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">gzip, deflate</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"User-Agent\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">User-Agent</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                        </collectionProp>\r\n"
				+ "                     </HeaderManager>\r\n"
				+ "                     <hashTree />\r\n"
				+ "                  </hashTree>\r\n"
				+ "                  <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"ntx/NTX/fonts/fa-solid-900.woff2-274\" enabled=\"true\">\r\n"
				+ "                     <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"Arguments.arguments\" />\r\n"
				+ "                     </elementProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.domain\">timntx.brazilsouth.cloudapp.azure.com</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.port\">8084</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.protocol\">http</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.contentEncoding\">UTF-8</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.path\">/NTX/fonts/fa-solid-900.woff2</stringProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.method\">GET</stringProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\r\n"
				+ "                     <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>\r\n"
				+ "                     <stringProp name=\"HTTPSampler.embedded_url_re\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.connect_timeout\" />\r\n"
				+ "                     <stringProp name=\"HTTPSampler.response_timeout\" />\r\n"
				+ "                  </HTTPSamplerProxy>\r\n"
				+ "                  <hashTree>\r\n"
				+ "                     <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" testname=\"HTTP Header Manager\" enabled=\"true\">\r\n"
				+ "                        <collectionProp name=\"HeaderManager.headers\">\r\n"
				+ "                           <elementProp name=\"Referer\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Referer</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">http://timntx.brazilsouth.cloudapp.azure.com:8084/NTX/libs/Fontawesome/solid.min.css</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept-Language\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Language</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept-Encoding\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept-Encoding</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">identity</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"User-Agent\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">User-Agent</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                           <elementProp name=\"Accept\" elementType=\"Header\">\r\n"
				+ "                              <stringProp name=\"Header.name\">Accept</stringProp>\r\n"
				+ "                              <stringProp name=\"Header.value\">application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8</stringProp>\r\n"
				+ "                           </elementProp>\r\n"
				+ "                        </collectionProp>\r\n"
				+ "                     </HeaderManager>\r\n"
				+ "                     <hashTree />\r\n"
				+ "                  </hashTree>\r\n"
				+ "               </hashTree>\r\n"
				+ "            </hashTree>\r\n"
				+ "            <ResultCollector guiclass=\"SimpleDataWriter\" testclass=\"ResultCollector\" testname=\"Escreve log de requisições em arquivo CSV\" enabled=\"true\">\r\n"
				+ "               <boolProp name=\"ResultCollector.error_logging\">false</boolProp>\r\n"
				+ "               <objProp>\r\n"
				+ "                  <name>saveConfig</name>\r\n"
				+ "                  <value class=\"SampleSaveConfiguration\">\r\n"
				+ "                     <time>true</time>\r\n"
				+ "                     <latency>true</latency>\r\n"
				+ "                     <timestamp>true</timestamp>\r\n"
				+ "                     <success>true</success>\r\n"
				+ "                     <label>true</label>\r\n"
				+ "                     <code>true</code>\r\n"
				+ "                     <message>true</message>\r\n"
				+ "                     <threadName>true</threadName>\r\n"
				+ "                     <dataType>true</dataType>\r\n"
				+ "                     <encoding>false</encoding>\r\n"
				+ "                     <assertions>true</assertions>\r\n"
				+ "                     <subresults>true</subresults>\r\n"
				+ "                     <responseData>false</responseData>\r\n"
				+ "                     <samplerData>false</samplerData>\r\n"
				+ "                     <xml>false</xml>\r\n"
				+ "                     <fieldNames>true</fieldNames>\r\n"
				+ "                     <responseHeaders>false</responseHeaders>\r\n"
				+ "                     <requestHeaders>false</requestHeaders>\r\n"
				+ "                     <responseDataOnError>false</responseDataOnError>\r\n"
				+ "                     <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>\r\n"
				+ "                     <assertionsResultsToSave>0</assertionsResultsToSave>\r\n"
				+ "                     <bytes>true</bytes>\r\n"
				+ "                     <sentBytes>true</sentBytes>\r\n"
				+ "                     <url>true</url>\r\n"
				+ "                     <threadCounts>true</threadCounts>\r\n"
				+ "                     <idleTime>true</idleTime>\r\n"
				+ "                     <connectTime>true</connectTime>\r\n"
				+ "                  </value>\r\n"
				+ "               </objProp>\r\n"
				+ "               <stringProp name=\"filename\">${SCRIPT_PATH}RESULTS_${__time(dd-MM-yyyy_HH-mm)}.csv</stringProp>\r\n"
				+ "            </ResultCollector>\r\n"
				+ "            <hashTree />\r\n"
				+ "            <ResultCollector guiclass=\"SimpleDataWriter\" testclass=\"ResultCollector\" testname=\"Escreve log de erros em arquivo XML\" enabled=\"true\">\r\n"
				+ "               <boolProp name=\"ResultCollector.error_logging\">true</boolProp>\r\n"
				+ "               <objProp>\r\n"
				+ "                  <name>saveConfig</name>\r\n"
				+ "                  <value class=\"SampleSaveConfiguration\">\r\n"
				+ "                     <time>true</time>\r\n"
				+ "                     <latency>true</latency>\r\n"
				+ "                     <timestamp>true</timestamp>\r\n"
				+ "                     <success>true</success>\r\n"
				+ "                     <label>true</label>\r\n"
				+ "                     <code>true</code>\r\n"
				+ "                     <message>true</message>\r\n"
				+ "                     <threadName>true</threadName>\r\n"
				+ "                     <dataType>true</dataType>\r\n"
				+ "                     <encoding>true</encoding>\r\n"
				+ "                     <assertions>true</assertions>\r\n"
				+ "                     <subresults>true</subresults>\r\n"
				+ "                     <responseData>true</responseData>\r\n"
				+ "                     <samplerData>true</samplerData>\r\n"
				+ "                     <xml>true</xml>\r\n"
				+ "                     <fieldNames>true</fieldNames>\r\n"
				+ "                     <responseHeaders>true</responseHeaders>\r\n"
				+ "                     <requestHeaders>true</requestHeaders>\r\n"
				+ "                     <responseDataOnError>false</responseDataOnError>\r\n"
				+ "                     <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>\r\n"
				+ "                     <assertionsResultsToSave>0</assertionsResultsToSave>\r\n"
				+ "                     <bytes>true</bytes>\r\n"
				+ "                     <sentBytes>true</sentBytes>\r\n"
				+ "                     <url>true</url>\r\n"
				+ "                     <fileName>true</fileName>\r\n"
				+ "                     <hostname>true</hostname>\r\n"
				+ "                     <threadCounts>true</threadCounts>\r\n"
				+ "                     <sampleCount>true</sampleCount>\r\n"
				+ "                     <idleTime>true</idleTime>\r\n"
				+ "                     <connectTime>true</connectTime>\r\n"
				+ "                  </value>\r\n"
				+ "               </objProp>\r\n"
				+ "               <stringProp name=\"filename\">${SCRIPT_PATH}RESULTS_${__time(dd-MM-yyyy_HH-mm)}.xml</stringProp>\r\n"
				+ "            </ResultCollector>\r\n"
				+ "            <hashTree />\r\n"
				+ "         </hashTree>\r\n"
				+ "         <ResultCollector guiclass=\"ViewResultsFullVisualizer\" testclass=\"ResultCollector\" testname=\"View Results Tree\" enabled=\"true\">\r\n"
				+ "            <boolProp name=\"ResultCollector.error_logging\">false</boolProp>\r\n"
				+ "            <objProp>\r\n"
				+ "               <name>saveConfig</name>\r\n"
				+ "               <value class=\"SampleSaveConfiguration\">\r\n"
				+ "                  <time>true</time>\r\n"
				+ "                  <latency>true</latency>\r\n"
				+ "                  <timestamp>true</timestamp>\r\n"
				+ "                  <success>true</success>\r\n"
				+ "                  <label>true</label>\r\n"
				+ "                  <code>true</code>\r\n"
				+ "                  <message>true</message>\r\n"
				+ "                  <threadName>true</threadName>\r\n"
				+ "                  <dataType>false</dataType>\r\n"
				+ "                  <encoding>false</encoding>\r\n"
				+ "                  <assertions>true</assertions>\r\n"
				+ "                  <subresults>false</subresults>\r\n"
				+ "                  <responseData>false</responseData>\r\n"
				+ "                  <samplerData>false</samplerData>\r\n"
				+ "                  <xml>false</xml>\r\n"
				+ "                  <fieldNames>true</fieldNames>\r\n"
				+ "                  <responseHeaders>false</responseHeaders>\r\n"
				+ "                  <requestHeaders>false</requestHeaders>\r\n"
				+ "                  <responseDataOnError>true</responseDataOnError>\r\n"
				+ "                  <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>\r\n"
				+ "                  <assertionsResultsToSave>0</assertionsResultsToSave>\r\n"
				+ "                  <bytes>true</bytes>\r\n"
				+ "                  <hostname>true</hostname>\r\n"
				+ "                  <threadCounts>true</threadCounts>\r\n"
				+ "                  <sampleCount>true</sampleCount>\r\n"
				+ "               </value>\r\n"
				+ "            </objProp>\r\n"
				+ "            <stringProp name=\"filename\" />\r\n"
				+ "         </ResultCollector>\r\n"
				+ "         <hashTree />\r\n"
				+ "         <ProxyControl guiclass=\"ProxyControlGui\" testclass=\"ProxyControl\" testname=\"HTTP(S) Test Script Recorder\" enabled=\"false\">\r\n"
				+ "            <stringProp name=\"ProxyControlGui.port\">5678</stringProp>\r\n"
				+ "            <collectionProp name=\"ProxyControlGui.exclude_list\">\r\n"
				+ "               <stringProp name=\"805311387\">windowsupdate\\.microsoft\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"1179605444\">(?i).*\\.(bmp|css|js|gif|ico|jpe?g|png|swf|eot|otf|ttf|mp4|woff|woff2)</stringProp>\r\n"
				+ "               <stringProp name=\"110431874\">.*msg\\.yahoo\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-88591710\">www\\.download\\.windowsupdate\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"1323576868\">toolbarqueries\\.google\\..*</stringProp>\r\n"
				+ "               <stringProp name=\"1739087931\">http?://self-repair\\.mozilla\\.org.*</stringProp>\r\n"
				+ "               <stringProp name=\"1206954446\">tiles.*\\.mozilla\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-1424663473\">.*detectportal\\.firefox\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"1779943373\">us\\.update\\.toolbar\\.yahoo\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-190610036\">.*\\.google\\.com.*/safebrowsing/.*</stringProp>\r\n"
				+ "               <stringProp name=\"-1899150273\">api\\.bing\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-958112859\">toolbar\\.google\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-192420923\">.*yimg\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-576820688\">toolbar\\.msn\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"305776760\">(?i).*\\.(bmp|css|js|gif|ico|jpe?g|png|swf|eot|otf|ttf|mp4|woff|woff2)[\\?;].*</stringProp>\r\n"
				+ "               <stringProp name=\"-1435252351\">toolbar\\.avg\\.com/.*</stringProp>\r\n"
				+ "               <stringProp name=\"2118375536\">www\\.google-analytics\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-1279148329\">pgq\\.yahoo\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"1815174768\">safebrowsing.*\\.google\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"-1314416226\">sqm\\.microsoft\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"587935979\">g\\.msn.*</stringProp>\r\n"
				+ "               <stringProp name=\"1629558731\">clients.*\\.google.*</stringProp>\r\n"
				+ "               <stringProp name=\"11072252\">.*toolbar\\.yahoo\\.com.*</stringProp>\r\n"
				+ "               <stringProp name=\"1726898318\">geo\\.yahoo\\.com.*</stringProp>\r\n"
				+ "            </collectionProp>\r\n"
				+ "            <collectionProp name=\"ProxyControlGui.include_list\" />\r\n"
				+ "            <boolProp name=\"ProxyControlGui.capture_http_headers\">true</boolProp>\r\n"
				+ "            <intProp name=\"ProxyControlGui.grouping_mode\">4</intProp>\r\n"
				+ "            <boolProp name=\"ProxyControlGui.add_assertion\">false</boolProp>\r\n"
				+ "            <stringProp name=\"ProxyControlGui.sampler_type_name\" />\r\n"
				+ "            <boolProp name=\"ProxyControlGui.sampler_redirect_automatically\">false</boolProp>\r\n"
				+ "            <boolProp name=\"ProxyControlGui.sampler_follow_redirects\">true</boolProp>\r\n"
				+ "            <boolProp name=\"ProxyControlGui.use_keepalive\">true</boolProp>\r\n"
				+ "            <boolProp name=\"ProxyControlGui.sampler_download_images\">false</boolProp>\r\n"
				+ "            <boolProp name=\"ProxyControlGui.regex_match\">true</boolProp>\r\n"
				+ "            <stringProp name=\"ProxyControlGui.content_type_include\" />\r\n"
				+ "            <stringProp name=\"ProxyControlGui.content_type_exclude\" />\r\n"
				+ "            <boolProp name=\"ProxyControlGui.notify_child_sl_filtered\">false</boolProp>\r\n"
				+ "            <stringProp name=\"ProxyControlGui.proxy_prefix_http_sampler_name\">ntx</stringProp>\r\n"
				+ "            <intProp name=\"ProxyControlGui.proxy_http_sampler_naming_mode\">0</intProp>\r\n"
				+ "            <stringProp name=\"ProxyControlGui.proxy_pause_http_sampler\" />\r\n"
				+ "            <boolProp name=\"ProxyControlGui.detect_graphql_request\">true</boolProp>\r\n"
				+ "            <stringProp name=\"ProxyControlGui.default_encoding\">UTF-8</stringProp>\r\n"
				+ "            <stringProp name=\"ProxyControlGui.domains\">timntx.brazilsouth.cloudapp.azure.com</stringProp>\r\n"
				+ "         </ProxyControl>\r\n"
				+ "         <hashTree>\r\n"
				+ "            <ResultCollector guiclass=\"ViewResultsFullVisualizer\" testclass=\"ResultCollector\" testname=\"View Results Tree\" enabled=\"true\">\r\n"
				+ "               <boolProp name=\"ResultCollector.error_logging\">false</boolProp>\r\n"
				+ "               <objProp>\r\n"
				+ "                  <name>saveConfig</name>\r\n"
				+ "                  <value class=\"SampleSaveConfiguration\">\r\n"
				+ "                     <time>true</time>\r\n"
				+ "                     <latency>true</latency>\r\n"
				+ "                     <timestamp>true</timestamp>\r\n"
				+ "                     <success>true</success>\r\n"
				+ "                     <label>true</label>\r\n"
				+ "                     <code>true</code>\r\n"
				+ "                     <message>true</message>\r\n"
				+ "                     <threadName>true</threadName>\r\n"
				+ "                     <dataType>true</dataType>\r\n"
				+ "                     <encoding>true</encoding>\r\n"
				+ "                     <assertions>true</assertions>\r\n"
				+ "                     <subresults>true</subresults>\r\n"
				+ "                     <responseData>true</responseData>\r\n"
				+ "                     <samplerData>true</samplerData>\r\n"
				+ "                     <xml>true</xml>\r\n"
				+ "                     <fieldNames>false</fieldNames>\r\n"
				+ "                     <responseHeaders>true</responseHeaders>\r\n"
				+ "                     <requestHeaders>true</requestHeaders>\r\n"
				+ "                     <responseDataOnError>true</responseDataOnError>\r\n"
				+ "                     <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>\r\n"
				+ "                     <assertionsResultsToSave>0</assertionsResultsToSave>\r\n"
				+ "                     <bytes>true</bytes>\r\n"
				+ "                     <url>true</url>\r\n"
				+ "                     <fileName>true</fileName>\r\n"
				+ "                     <hostname>true</hostname>\r\n"
				+ "                     <threadCounts>true</threadCounts>\r\n"
				+ "                     <sampleCount>true</sampleCount>\r\n"
				+ "                     <idleTime>true</idleTime>\r\n"
				+ "                     <connectTime>true</connectTime>\r\n"
				+ "                  </value>\r\n"
				+ "               </objProp>\r\n"
				+ "               <stringProp name=\"filename\">recording.xml</stringProp>\r\n"
				+ "            </ResultCollector>\r\n"
				+ "            <hashTree />\r\n"
				+ "         </hashTree>\r\n"
				+ "      </hashTree>\r\n"
				+ "   </hashTree>\r\n"
				+ "</jmeterTestPlan>");
	}
}